--- 
- hosts: localhost 
  become: true
  tasks:
  - name: Install boto3
    pip:
      name: 
        - boto
        - boto3 
      state: present

 

  - name: Create S3 bucket
    s3_bucket:
      name: cloudiartest123
      state: present